"""harden database constraints

Revision ID: a43c0c3ee9c3
Revises: caa18a97aadb
Create Date: 2026-09-26 13:27:11.900315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a43c0c3ee9c3'
down_revision: Union[str, Sequence[str], None] = 'caa18a97aadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'centre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'appointment_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bookings', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('centre_tests', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('centre_tests', 'centre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('centre_tests', 'test_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.create_unique_constraint('uq_centre_test', 'centre_tests', ['centre_id', 'test_id'])
    op.alter_column('diagnostic_centres', 'centre_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('diagnostic_centres', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('diagnostic_tests', 'test_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('payments', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('webhook_events', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('webhook_events', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('webhook_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('webhook_events', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('webhook_events', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('payments', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('diagnostic_tests', 'test_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('diagnostic_centres', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('diagnostic_centres', 'centre_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('uq_centre_test', 'centre_tests', type_='unique')
    op.alter_column('centre_tests', 'test_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('centre_tests', 'centre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('centre_tests', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bookings', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('bookings', 'appointment_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'centre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
